### ISSUE TITLE
Стили

### ISSUE THREAD

**Issue by rsilivestr** [mvodev/FSDCourse2#22]
![image](https://user-images.githubusercontent.com/31914503/128717247-242cb200-71e3-4ccd-9a2c-4dd689ef2b37.png)

Когда padding/margin симметричны - лучше использовать краткую запись (и не стоит добавлять единицы измерения к нулям):

```css
padding: 0 15px;
```

**Comment by rsilivestr** [comment]
Встречаются стили, не влияющие на отображение. Например, если на странице регистрации удалить у узла `<main>` класс 'reg-wrapper' - изменится только высота (на правильную, кстати - в макете высота секции с картинкой явно не 100% от body по высоте).

Такие "мёртвые" стили лучше убрать или переработать.

**Comment by rsilivestr** [comment]
Всё ещё есть над чем работать. На примере страниц входа и регистрации, необходимый минимум вложенности и стилей:

```pug
//- вход
main.main.main_page_sign-in.main_center_both
  +signin({action:'#'})
//- регистрация
main.main.main_centered.main_page_register
  +signup({action:'#'})
```

```scss
// такой блок .main должен в принципе подойти для всех страниц
.main {
  // можно заменить на align-self: flex-end для футеров
  flex-grow: 1;
  // вертикальные отступы на случай, если высота контента увеличится
  // возможно, их стоит вынести в модификатор, если есть контент,
  // который должен прилегать к верху или низу блока
  padding: 20px 0;

  // для простого позиционирования по центру обёртки не обязательны,
  // достаточно модификатора для родительского блока
  &_centered {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  &_page {
    // страницы отличаются только высотой и фоном
    // хотя разная высота может быть ошибкой дизайна
	// на проектах бывают неточности дизайна, когда есть сомнения - стоит уточнять
    &_sign-in {
      min-height: 702px;
      background: center / cover no-repeat
        url('../assets/img/jpg/registration.jpg');
    }

    &_register {
      min-height: 684px;
      background: center / cover no-repeat
        url("../assets/img/jpg/registration.jpg")
    }
  }
}
```

**Comment by rsilivestr** [comment]
По ТЗ минимальная ширина - 320px. Формы явно не масштабируюся.

Вместо фиксированной ширины лучше задавать максимальную, как для формы, так и для инпутов (`width: 100%; max-width: XXXpx`). А вместо центрирования инпутов через маргины (когда надо согласовывать максимальную ширину инпутов и формы), стоит задать форме padding, а контенту позволить растягиваться на всю ширину:

```scss
.form {
  width: 100%;
  max-width: 320px;
  padding: 20px 10px;

  @media screen and (min-width: $desktop) {
    // или вместо media query можно задать динамические паддинги
    // зависящие от vw через функцию clamp
	padding: 30px 20px;
  }
}
```
